# **One-Hot Encoding in NLP**
In one-hot encoding each unique word is mapped to a binary vector where only one position has the value 1 and all others are 0. The length of the vector equals the size of the vocabulary making each word uniquely identifiable.

- Transforms categorical text data into numeric vectors
- Each word is represented by a vector with a single 1 and remaining 0s
- Easy to understand and implement
- Works well for small vocabularies but becomes inefficient for large ones

In [1]:
import numpy as np
import string
import matplotlib.pyplot as plt

### **Define the Corpus**

- A corpus is a collection of sentences on which we want to perform NLP tasks.
- Each sentence will later be tokenized and encoded.

In [2]:
corpus = [
    "The quick brown fox jumps over the lazy dog",
    "The dog chased the fox",
    "The fox is quick and smart"
]

### **Preprocess Text**

- Convert text to lowercase to maintain consistency.
- Remove punctuation to avoid treating punctuations as separate tokens.
- Split the sentence into individual words.

In [8]:
def preprocess_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text.split()
tokenized_corpus = [preprocess_text(sentence) for sentence in corpus]
print(tokenized_corpus)

[['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog'], ['the', 'dog', 'chased', 'the', 'fox'], ['the', 'fox', 'is', 'quick', 'and', 'smart']]


### **Build Vocabulary**

- A vocabulary contains all unique words across the corpus.
- Sorting helps maintain a consistent order.
- We also create a dictionary to map each word to a unique index.

In [7]:
vocabulary = sorted(set(word for sentence in tokenized_corpus for word in sentence))
word_to_index = {word: idx for idx, word in enumerate(vocabulary)}
print(word_to_index)

{'and': 0, 'brown': 1, 'chased': 2, 'dog': 3, 'fox': 4, 'is': 5, 'jumps': 6, 'lazy': 7, 'over': 8, 'quick': 9, 'smart': 10, 'the': 11}


### **One-Hot Encode Sentences**

- For each word create a zero vector of length equal to vocabulary size.
- Set the index corresponding to the word to 1.
- Collect all word vectors for a sentence.

In [9]:
def one_hot_encode(sentence, word_to_index):
    vocab_size = len(word_to_index)
    encoded_sentence = []
    for word in sentence:
        vector = np.zeros(vocab_size, dtype=int)
        vector[word_to_index[word]] = 1
        encoded_sentence.append(vector)
    return np.array(encoded_sentence)
encoded_vectors = one_hot_encode(tokenized_corpus[0], word_to_index)
print(encoded_vectors)

[[0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]]


In [10]:
print("Vocabulary:")
print(vocabulary)

print("\nOne-Hot Encoded Vectors (First Sentence):")
for word, vector in zip(tokenized_corpus[0], encoded_vectors):
    print(f"{word}: {vector}")

Vocabulary:
['and', 'brown', 'chased', 'dog', 'fox', 'is', 'jumps', 'lazy', 'over', 'quick', 'smart', 'the']

One-Hot Encoded Vectors (First Sentence):
the: [0 0 0 0 0 0 0 0 0 0 0 1]
quick: [0 0 0 0 0 0 0 0 0 1 0 0]
brown: [0 1 0 0 0 0 0 0 0 0 0 0]
fox: [0 0 0 0 1 0 0 0 0 0 0 0]
jumps: [0 0 0 0 0 0 1 0 0 0 0 0]
over: [0 0 0 0 0 0 0 0 1 0 0 0]
the: [0 0 0 0 0 0 0 0 0 0 0 1]
lazy: [0 0 0 0 0 0 0 1 0 0 0 0]
dog: [0 0 0 1 0 0 0 0 0 0 0 0]
